repos:
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        args: ["--line-length", "79"]
  - repo: https://gitlab.com/daverona-env/pre-commit-cpp
    rev: master
    hooks:
      - id: clang-format
        name: clang-format
        args: [-style=file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: flake8
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
    rev: master
    hooks:
      - id: cmake-format
        exclude: build
